/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { InfoContract } from "./InfoContract";
export type { Migrations } from "./Migrations";
export * as factories from "./factories";
export { InfoContract__factory } from "./factories/InfoContract__factory";
export { Migrations__factory } from "./factories/Migrations__factory";
